plugins:
  - serverless-webpack
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-offline
service: ngcontact
custom:
  webpack:
    webpackConfig: webpack.config.js
provider:
  name: aws
  runtime: nodejs22.x
package:
  exclude:
    - '*.sh'
    - 'README.md'
functions:
  ngcontact:
    handler: handler.contact
    events:
      - http:
          path: ngcontact
          method: post
